### ISSUE TITLE
Ergonomic component initialization and access to data containers

### ISSUE THREAD

**Issue by k88hudson-cfa** [CDCgov/ixa#6]
As designed, the `Context` current has no concept of ownership for components.

We want components to be able to do a few different things, including initialize, in the right order and access data containers from `Context`. Right now the ergonomics of this is not great, i.e. it involves having to call `context.get_data_container::<PluginType>()`, and it would be nice to figure out a better way to do this.

**Comment by ekr-cfa** [comment]
This issue is fixed.
